@startuml Rubber Duck Cannot Fly
abstract class Duck{
    +Swin()
    +Quack()
    +Fly()
    {abstract} +Display()
}

class MallarDuck extends Duck{
    +Display() 
}

class RedHeadDuck extends Duck{
    +Display()
}

class RubberDuck extends Duck{
    +Quack()
    +Display()
    +Fly()
}
@enduml